"""initial schema with ingredient category

Revision ID: 5924f62e0b53
Revises: 
Create Date: 2026-06-07 07:03:20.378960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5924f62e0b53'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('market_unit', sa.String(length=20), nullable=False),
    sa.Column('unit_price_xaf', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('household_size', sa.Integer(), nullable=True),
    sa.Column('preferred_budget', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('cooking_frequency', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ingredient_allergen',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('allergen', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_name', sa.String(length=150), nullable=False),
    sa.Column('cuisine_type', sa.String(length=50), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('meal_id')
    )
    op.create_table('meal_plan',
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_budget', sa.Float(), nullable=False),
    sa.Column('cooking_frequency', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('plan_id')
    )
    op.create_table('unit_conversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('cooking_unit', sa.String(length=20), nullable=False),
    sa.Column('market_unit', sa.String(length=20), nullable=False),
    sa.Column('conversion_factor', sa.Float(), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'cooking_unit', name='unique_conversion_per_unit')
    )
    op.create_table('user_allergy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('allergen', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_diet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('diet_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('estimated_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grocery_list',
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('list_id')
    )
    op.create_table('meal_diet_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('diet_type', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.meal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meal_ingredient',
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('cooking_unit', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.meal_id'], ),
    sa.PrimaryKeyConstraint('meal_id', 'ingredient_id')
    )
    op.create_table('meal_plan_meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.meal_id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['meal_plan.plan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grocery_list_item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('custom_name', sa.String(length=150), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['grocery_list.list_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grocery_list_item')
    op.drop_table('meal_plan_meal')
    op.drop_table('meal_ingredient')
    op.drop_table('meal_diet_tag')
    op.drop_table('grocery_list')
    op.drop_table('user_ingredient')
    op.drop_table('user_diet')
    op.drop_table('user_allergy')
    op.drop_table('unit_conversion')
    op.drop_table('meal_plan')
    op.drop_table('meal')
    op.drop_table('ingredient_allergen')
    op.drop_table('user')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
