"""add persistent always_at_home with counter

Revision ID: 80e3c06dd52d
Revises: d249f5b69eb5
Create Date: 2026-06-10 03:08:54.446475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80e3c06dd52d'
down_revision = 'd249f5b69eb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_ingredient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_gli_user_ingredient', 'user_ingredient', ['user_ingredient_id'], ['id'])

    with op.batch_alter_table('user_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('always_at_home', sa.Boolean(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('plan_counter', sa.Integer(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_ingredient', schema=None) as batch_op:
        batch_op.drop_column('plan_counter')
        batch_op.drop_column('always_at_home')

    with op.batch_alter_table('grocery_list_item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_gli_user_ingredient', type_='foreignkey')
        batch_op.drop_column('user_ingredient_id')

    # ### end Alembic commands ###
