"""add always_at_home to grocery_list_item

Revision ID: d249f5b69eb5
Revises: 5924f62e0b53
Create Date: 2026-06-08 12:24:04.474673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd249f5b69eb5'
down_revision = '5924f62e0b53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_list_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('always_at_home', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grocery_list_item', schema=None) as batch_op:
        batch_op.drop_column('always_at_home')

    # ### end Alembic commands ###
